// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MultiAccSlot","status":true,"description":"Allow more than 1 slot per equip type.","parameters":{}},
{"name":"TF_ExtraSelfSwitches","status":true,"description":"Added self switches from E to Z","parameters":{}}
];
